server:
  port: 8080

spring:
  datasource:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
